name: "Benchmarks"

on:
  workflow_dispatch:
  schedule:
      - cron: "37 */12 * * *"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install benchmark dependencies
        run: |
          python -m pip install qa/tools
          python -m pip install -r qa/benchmarks/requirements.txt
      - name: Run benchmark pytest suite
        shell: bash
        run: |
          set -o pipefail
          cd qa/benchmarks
          mkdir report
          mkdir tmp_path_root
          pytest \
            -vv \
            --log-cli-level=INFO \
            --random-subset=1 \
            --html report/report.html --self-contained-html \
            --basetemp=tmp_path_root \
            --upload-assets-s3-bucket="apex-benchmarks" | tee pytest_output.txt
        env:
          OPENEO_AUTH_METHOD: client_credentials
          OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED }}
          OPENEO_AUTH_CLIENT_CREDENTIALS_EGI: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_EGI }}
          OPENEO_AUTH_CLIENT_CREDENTIALS_TERRASCOPE: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_TERRASCOPE }}
          APEX_ALGORITHMS_S3_ACCESS_KEY_ID: ${{ secrets.APEX_ALGORITHMS_S3_ACCESS_KEY_ID }}
          APEX_ALGORITHMS_S3_SECRET_ACCESS_KEY: ${{ secrets.APEX_ALGORITHMS_S3_SECRET_ACCESS_KEY }}
          APEX_ALGORITHMS_S3_ENDPOINT_URL: "https://s3.waw3-1.cloudferro.com"
          APEX_ALGORITHMS_S3_DEFAULT_REGION: "waw3-1"


      - name: Handle Benchmark Results
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_REPO: ${{ github.repository }}
        run: python qa/tools/apex_algorithm_qa_tools/issue_handler.py 

      - name: List local reports
        if: ${{ !cancelled() }}
        run: ls -alR qa/benchmarks/report
      - name: List local results
        if: ${{ !cancelled() }}
        run: ls -alR qa/benchmarks/tmp_path_root
      - name: upload report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: report
          path: qa/benchmarks/report/
