name: "Benchmarks"

on:
  workflow_dispatch:
  schedule:
      - cron: "37 12 * * *"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install benchmark dependencies
        run: |
          python -m pip install qa/tools
          python -m pip install -r qa/benchmarks/requirements.txt
      - name: Test with pytest
        run: |
          cd qa/benchmarks
          pytest --random-subset=1
        env:
          OPENEO_AUTH_METHOD: client_credentials
          OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED }}
