name: "Benchmarks"

on:
  workflow_dispatch:
  schedule:
      - cron: "37 12 * * *"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install benchmark dependencies
        run: |
          python -m pip install qa/tools
          python -m pip install -r qa/benchmarks/requirements.txt
      - name: Test with pytest
        run: |
          cd qa/benchmarks
          mkdir report
          pytest -k dummy --html report/report.html --self-contained-html --test-metrics=report/metrics.json
        env:
          OPENEO_AUTH_METHOD: client_credentials
          OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED }}
      - name: upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: qa/benchmarks/report/
