name: "Benchmark (specific)"

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: "Scenario name filter (passed to pytest -k). For example: 'biopar'"
        required: true
        type: string

permissions:
  contents: read
  issues: write
jobs:
  benchmarks:
    uses: ./.github/workflows/_run_benchmarks.yaml
    with:
      scenario: ${{ inputs.scenario }}
    secrets:
      OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_CDSEFED }}
      OPENEO_AUTH_CLIENT_CREDENTIALS_EGI: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_EGI }}
      OPENEO_AUTH_CLIENT_CREDENTIALS_TERRASCOPE: ${{ secrets.OPENEO_AUTH_CLIENT_CREDENTIALS_TERRASCOPE }}
      APEX_ALGORITHMS_S3_ACCESS_KEY_ID: ${{ secrets.APEX_ALGORITHMS_S3_ACCESS_KEY_ID }}
      APEX_ALGORITHMS_S3_SECRET_ACCESS_KEY: ${{ secrets.APEX_ALGORITHMS_S3_SECRET_ACCESS_KEY }}
