name: Preview catalogue web from data PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'algorithm_catalog/**'

permissions:
  contents: read

jobs:
  notify-catalogue-web:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger preview pipeline to catalogue web repo
        env:
          GH_TOKEN: ${{ secrets.CATALOGUE_REPOSITORY_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          WEB_REPOSITORY: apex-algorithms-catalogue-web
          EVENT_TYPE: ${{ github.event.action == 'closed' && 'catalogue-pr-closed' || 'catalogue-pr-updated' }}
        run: |
          pr_number='${{ github.event.pull_request.number }}'
          head_ref='${{ github.event.pull_request.head.ref }}'
          head_sha='${{ github.event.pull_request.head.sha }}'
          head_repo='${{ github.event.pull_request.head.repo.full_name }}'
          catalogue_repo='${{ github.repository }}'

          gh api repos/$REPOSITORY_OWNER/$WEB_REPOSITORY/dispatches \
            -f event_type="$EVENT_TYPE" \
            -F client_payload[pr_number]="$pr_number" \
            -F client_payload[head_ref]="$head_ref" \
            -F client_payload[head_sha]="$head_sha" \
            -F client_payload[head_repo]="$head_repo" \
            -F client_payload[catalogue_repo]="$catalogue_repo"
